=== xxxandriyxxx/task14_xml/src/main/resources/xml/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="tariffs"
           xmlns="tariffs"
           elementFormDefault="qualified">

    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tariff" type="tariffType" minOccurs="0"
                            maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tariffType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="operator_name" type="xs:string"/>
            <xs:element name="payroll">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0.0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="call_prices">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="inside">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="outside">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="landline_phone">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="100"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="sms_price">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="100"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="parameters">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="favorite_numbers">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="tariffing">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="per_15_seconds"/>
                                    <xs:enumeration value="per_1_minute"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="connection_payment">
                            <xs:simpleType>
                                <xs:restriction base="xs:decimal">
                                    <xs:minInclusive value="0.0"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="tariffNo" type="xs:integer">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="1"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


</xs:schema>

=== xxxandriyxxx/task14_xml/src/main/resources/xml/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="tariffs.xsl"?>

<tariffs xmlns="tariffs"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="tariffs.xsd">
    <tariff tariffNo="1">
        <name>qwe</name>
        <operator_name>bbb</operator_name>
        <payroll>10000</payroll>
        <call_prices>
            <inside>0</inside>
            <outside>23</outside>
            <landline_phone>80</landline_phone>
        </call_prices>
        <sms_price>100</sms_price>
        <parameters>
            <favorite_numbers>1</favorite_numbers>
            <tariffing>per_1_minute</tariffing>
            <connection_payment>0.23</connection_payment>
        </parameters>
    </tariff>
</tariffs>
